structures/urls.py
"""Tasks for Structures."""

from django.urls import path
from django.views.decorators.cache import never_cache

from .views import public, statistics, status, structures

app_name = "structures"

urlpatterns = [
    path("", structures.index, name="index"),
    path("list", structures.structure_list, name="structure_list"),
    path(
        "structure_list_data/<str:selection>",
        structures.structure_list_data,
        name="structure_list_data",
    ),
    path(
        "add_structure_owner",
        structures.add_structure_owner,
        name="add_structure_owner",
    ),
    path("service_status", never_cache(status.service_status), name="service_status"),
    path(
        "<int:structure_id>/structure_details",
        structures.structure_details,
        name="structure_details",
    ),
    path(
        "<int:structure_id>/poco_details",
        structures.poco_details,
        name="poco_details",
    ),
    path(
        "<int:structure_id>/starbase_detail",
        structures.starbase_detail,
        name="starbase_detail",
    ),
    # public
    path("public", public.public, name="public"),
    path(
        "public_poco_list_data/<int:character_id>",
        public.public_poco_list_data,
        name="public_poco_list_data",
    ),
    # statistics
    path("statistics", statistics.statistics, name="statistics"),
    path(
        "summary_data", statistics.structure_summary_data, name="structure_summary_data"
    ),
]

structures/views/public.py
"""Views for public page."""

from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from allianceauth.eveonline.models import EveCharacter
from allianceauth.services.hooks import get_extension_logger
from app_utils.logging import LoggerAddTag

from structures import __title__
from structures.constants import EveCategoryId
from structures.core.serializers import PocoListSerializer
from structures.models import Structure

from .common import add_common_context, add_common_data_export

logger = LoggerAddTag(get_extension_logger(__name__), __title__)


@login_required
@permission_required("structures.basic_access")
def public(request: HttpRequest) -> HttpResponse:
    """Return view to render Public page."""
    characters = (
        EveCharacter.objects.filter(character_ownership__user=request.user)
        .order_by("character_name")
        .values("character_id", "character_name")
    )
    character_id = int(request.GET.get("character_id", 0))
    if not character_id:
        try:
            character_id = request.user.profile.main_character.character_id
        except AttributeError:
            character_id = None

    pocos_count = _public_pocos_query().count()
    selected_character = get_object_or_404(EveCharacter, character_id=character_id)

    ajax_url = reverse(
        "structures:public_poco_list_data", args=[selected_character.character_id]
    )
    data_export = add_common_data_export(
        {
            "ajax_url": ajax_url,
            "filter_titles": {
                "alliance": _("Alliance"),
                "access": _("Access?"),
                "corporation": _("Corporation"),
                "constellation": _("Constellation"),
                "planet_type": _("Planet Type"),
                "region": _("Region"),
                "space_type": _("Space Type"),
                "solar_system": _("Solar System"),
            },
        }
    )
    context = {
        "characters": characters,
        "selected_character": selected_character,
        "pocos_count": pocos_count,
        "data_export": data_export,
    }
    return render(request, "structures/public.html", add_common_context(context))


def public_poco_list_data(request: HttpRequest, character_id: int) -> JsonResponse:
    """List of public POCOs for DataTables."""
    character = get_object_or_404(EveCharacter, character_id=character_id)
    pocos = _public_pocos_query()
    serializer = PocoListSerializer(
        queryset=pocos, request=request, character=character
    )
    data = serializer.to_list()
    return JsonResponse({"data": data})


def _public_pocos_query():
    pocos = Structure.objects.select_related_defaults().filter(
        eve_type__eve_group__eve_category_id=EveCategoryId.ORBITAL,
        owner__are_pocos_public=True,
    )
    return pocos

structures/views/statistics.py
"""Views for statistics page."""

from django.contrib.auth.decorators import login_required, permission_required
from django.db.models import Count, F, Q
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from eveuniverse.core import dotlan, eveimageserver

from allianceauth.services.hooks import get_extension_logger
from app_utils.logging import LoggerAddTag
from app_utils.views import link_html

from structures import __title__
from structures.constants import EveCategoryId, EveGroupId, EveTypeId
from structures.helpers import floating_icon_with_text_html
from structures.models import Structure

from .common import add_common_context, add_common_data_export

logger = LoggerAddTag(get_extension_logger(__name__), __title__)


def _default_if_none(value, default=None):
    """Return default if a value is None."""
    if value is None:
        return default
    return value


@login_required
@permission_required("structures.basic_access")
def statistics(request: HttpRequest) -> HttpResponse:
    """Return view to render Statistics page."""
    ajax_url = reverse("structures:structure_summary_data")
    data_export = add_common_data_export(
        {
            "ajax_url": ajax_url,
            "filter_titles": {"alliance": _("Alliance")},
        }
    )
    context = {"data_export": data_export}
    return render(request, "structures/statistics.html", add_common_context(context))


@login_required
@permission_required("structures.basic_access")
def structure_summary_data(request: HttpRequest) -> JsonResponse:
    """View returning data for structure summary page."""
    summary_qs = (
        Structure.objects.visible_for_user(request.user)
        .values(
            corporation_id=F("owner__corporation__corporation_id"),
            corporation_name=F("owner__corporation__corporation_name"),
            alliance_name=F("owner__corporation__alliance__alliance_name"),
            alliance_ticker=F("owner__corporation__alliance__alliance_ticker"),
        )
        .annotate(
            ec_count=Count(
                "id", filter=Q(eve_type__eve_group=EveGroupId.ENGINEERING_COMPLEX)
            )
        )
        .annotate(
            refinery_count=Count(
                "id", filter=Q(eve_type__eve_group=EveGroupId.REFINERY)
            )
        )
        .annotate(
            citadel_count=Count("id", filter=Q(eve_type__eve_group=EveGroupId.CITADEL))
        )
        .annotate(
            upwell_count=Count(
                "id",
                filter=Q(eve_type__eve_group__eve_category=EveCategoryId.STRUCTURE),
            )
        )
        .annotate(poco_count=Count("id", filter=Q(eve_type=EveTypeId.CUSTOMS_OFFICE)))
        .annotate(
            starbase_count=Count(
                "id", filter=Q(eve_type__eve_group__eve_category=EveCategoryId.STARBASE)
            )
        )
    )
    data = []
    for row in summary_qs:
        other_count = (
            row["upwell_count"]
            - row["ec_count"]
            - row["refinery_count"]
            - row["citadel_count"]
        )
        total = row["upwell_count"] + row["poco_count"] + row["starbase_count"]

        corporation_id = row["corporation_id"]
        corporation_name = row["corporation_name"]
        alliance_name = _default_if_none(row["alliance_name"], "")
        alliance_ticker = _default_if_none(row["alliance_ticker"], "")
        corporation_icon_url = eveimageserver.corporation_logo_url(
            corporation_id, size=64
        )
        owner_link = link_html(
            dotlan.corporation_url(corporation_name), corporation_name
        )
        owner_display_html = floating_icon_with_text_html(
            corporation_icon_url, [owner_link, alliance_ticker]
        )
        owner_html = {"display": owner_display_html, "value": corporation_name}
        alliance_name_str = (
            f"{alliance_name} [{alliance_ticker}]" if alliance_ticker else alliance_name
        )

        data.append(
            {
                "id": int(corporation_id),
                "owner": owner_html,
                "corporation_name": corporation_name,
                "alliance_name": alliance_name_str,
                "citadel_count": row["citadel_count"],
                "ec_count": row["ec_count"],
                "refinery_count": row["refinery_count"],
                "other_count": other_count,
                "poco_count": row["poco_count"],
                "starbase_count": row["starbase_count"],
                "total": total,
            }
        )
    return JsonResponse({"data": data})

structures/templates/structures/base.html
{% extends 'allianceauth/base.html' %}
{% load i18n %}

{% block page_title %}{% translate "Structures" %}{% endblock %}

{% block content %}
    <br />
    <div>
        {% include 'structures/partials/menu.html' %}
        <h2 class="text-left">{{ page_title }}</h2>
        {% block details %}{% endblock %}
    </div>
{% endblock %}

structures/templates/structures/public.html
{% extends 'structures/base.html' %}
{% load i18n %}
{% load static %}
{% load humanize %}

{% block details %}

    <span class="pull-right">
        <form class="form-inline">
            <select
                class="form-control"
                name="character_id"
                style="height: auto;"
                onchange="this.form.submit()"
                title="Character for calculating access and tax">
                    {% for character in characters %}
                        <option
                            value="{{ character.character_id }}"
                            {% if character.character_id == selected_character.character_id %} selected{% endif %}>
                                {{ character.character_name }}
                        </option>
                    {% endfor %}
            </select>
        </form>
    </span>

    <!-- Nav tabs -->
    <ul id="public-tabs" class="nav nav-tabs" role="tablist">

        <li role="presentation" class="active">
            <a href="#pocos" aria-controls="orbitals" role="tab" data-toggle="tab">
                {% translate "Customs Offices" %} <small>({{ pocos_count|default:"-" }})</small>
            </a>
        </li>

    </ul>

    <div class="panel panel-default panel-tabs">
        <div class="panel-body">
            <div class="tab-content">

                <div role="tabpanel" class="tab-pane active" id="orbitals">
                    {% include "structures/partials/public/poco_list.html" %}
                </div>

            </div>

            <p class="text-muted">
                {% translate "Non corporation or alliance members will be assumed to have neutral standing with the owner" %} •
                {% translate "Data can be outdated by up to 1 hour due to API caching" %} •
                {% translate "Last updated" %} {{ last_updated|naturaltime|default:"?" }}
            </p>

        </div>
    </div>

    <!-- Export to Javascript -->
    {{ data_export|json_script:"export-data" }}

{% endblock %}

{% block extra_javascript %}
    {% include 'bundles/datatables-js.html' %}
    <script
        type="application/javascript"
        src="{% static 'structures/vendor/datatables/plugins/dataTables.rowGroup.min.js' %}">
    </script>
    <script
        type="application/javascript"
        src="{% static 'structures/vendor/datatables/plugins/filterDropDown.min.js' %}">
    </script>
    <script type="application/javascript" src="{% static 'structures/js/global.js' %}"></script>
    <script type="application/javascript" src="{% static 'structures/js/public.js' %}"></script>
{% endblock %}

{% block extra_css %}
    {% include 'bundles/datatables-css.html' %}

    <link
        rel="stylesheet"
        href="{% static 'memberaudit/vendor/datatables/plugins/rowGroup.dataTables.min.css' %}"
        type="text/css">

    <link rel="stylesheet" href="{% static 'structures/css/global.css' %}" type="text/css" media="screen">
    <link rel="stylesheet" href="{% static 'structures/css/main.css' %}" type="text/css" media="screen">
    <link rel="stylesheet" href="{% static 'structures/css/public.css' %}" type="text/css" media="screen">
{% endblock %}

{% block extra_script %}

{% endblock %}

structures/templates/structures/statistics.html
{% extends 'structures/base.html' %}
{% load i18n %}
{% load static %}
{% load humanize %}

{% block details %}

    <!-- Nav tabs -->
    <ul id="statistics-tabs" class="nav nav-tabs" role="tablist">

        <li role="presentation" class="active">
            <a href="#summary" aria-controls="summary" role="tab" data-toggle="tab">{% trans "Summary" %}</a>
        </li>

    </ul>

    <div class="panel panel-default panel-tabs">
        <div class="panel-body">
            <div class="tab-content">

                <div role="tabpanel" class="tab-pane active" id="summary">
                    {% include "structures/partials/statistics/structure_summary.html" %}
                </div>

            </div>
        </div>
    </div>

    <!-- Export to Javascript -->
    {{ data_export|json_script:"export-data" }}

{% endblock %}

{% block extra_javascript %}
    {% include 'bundles/datatables-js.html' %}
    <script
        type="application/javascript"
        src="{% static 'structures/vendor/datatables/plugins/filterDropDown.min.js' %}">
    </script>
    <script type="application/javascript" src="{% static 'structures/js/global.js' %}"></script>
    <script type="application/javascript" src="{% static 'structures/js/statistics.js' %}"></script>

{% endblock %}

{% block extra_css %}
    {% include 'bundles/datatables-css.html' %}

    <link rel="stylesheet" href="{% static 'structures/css/global.css' %}" type="text/css" media="screen">
    <link rel="stylesheet" href="{% static 'structures/css/main.css' %}" type="text/css" media="screen">
    <link rel="stylesheet" href="{% static 'structures/css/statistics.css' %}" type="text/css" media="screen">
{% endblock %}

{% block extra_script %}

{% endblock %}

structures/templates/structures/structures.html
{% extends 'structures/base.html' %}
{% load i18n %}
{% load bootstrap %}
{% load static %}
{% load humanize %}

{% block details %}

    <!-- Tags Filter Button -->
    <span class="pull-right">
        {% if tags_exist %}
            {% if active_tags %}
                <button
                    type="button"
                    class="btn btn-warning btn-tabs"
                    data-toggle="modal"
                    data-target="#modalTagsFilter">
                        {% translate "Tags Filter (Active)" %}
                </button>
            {% else %}
                <button
                    type="button"
                    class="btn btn-default btn-tabs"
                    data-toggle="modal"
                    data-target="#modalTagsFilter">
                        {% translate "Tags Filter" %}
                </button>
            {% endif %}
        {% else %}
            <button
                type="button"
                class="btn btn-default btn-tabs"
                data-toggle="modal"
                data-target="#modalTagsFilter"
                disabled="disabled">
                    {% translate "Tags Filter" %}
            </button>
        {% endif %}
    </span>

    <!-- Nav tabs -->
    <ul id="structure-tabs" class="nav nav-tabs" role="tablist">

        <li role="presentation">
            <a href="#structures" aria-controls="structures" role="tab" data-toggle="tab">
                {% trans "Upwell Structures" %} <small>({{ structures_count|default:"-" }})</small>
            </a>
        </li>

        <li role="presentation">
            <a href="#orbitals" aria-controls="orbitals" role="tab" data-toggle="tab">
                {% trans "Orbitals" %} <small>({{ orbitals_count|default:"-" }})</small>
            </a>
        </li>

        <li role="presentation">
            <a href="#starbases" aria-controls="starbases" role="tab" data-toggle="tab">
                {% trans "Starbases" %} <small>({{ starbases_count|default:"-" }})</small>
            </a>
        </li>

        {% if show_jump_gates_tab %}
            <li role="presentation">
                <a href="#jump-gates" aria-controls="jump-gates" role="tab" data-toggle="tab">
                    {% trans "Jump Gates" %} <small>({{ jump_gates_count|default:"-" }})</small>
                </a>
            </li>
        {% endif %}

    </ul>

    <div class="panel panel-default panel-tabs">
        <div class="panel-body">
            <div class="tab-content">

                <div role="tabpanel" class="tab-pane" id="structures">
                    {% include "structures/partials/structures/structure_list.html" %}
                </div>

                <div role="tabpanel" class="tab-pane" id="orbitals">
                    {% include "structures/partials/structures/orbital_list.html" %}
                </div>

                <div role="tabpanel" class="tab-pane" id="starbases">
                    {% include "structures/partials/structures/starbase_list.html" %}
                </div>

                {% if show_jump_gates_tab %}
                    <div role="tabpanel" class="tab-pane" id="jump-gates">
                        {% include "structures/partials/structures/jump_gate_list.html" %}
                    </div>
                {% endif %}

                <p class="text-muted">
                    {% translate "All dates are EVE time" %}
                    | {% translate "Data can be outdated by up to 1 hour due to API caching" %}
                    | {% translate "Last updated" %} {{ last_updated|naturaltime|default:"?" }}
                </p>

            </div>

        </div>
    </div>

    <!-- Tags Filter Modal -->
    <div class="modal" id="modalTagsFilter" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <form method="post">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title">{% translate "Tags Filter" %}</h4>
                    </div>
                    <div class="modal-body">
                        {% csrf_token %}
                        {{ tags_filter_form|bootstrap }}
                    </div>
                    <div class="modal-footer">
                        <a class="btn btn-default pull-left" href="{% url 'structures:index' %}" role="button">
                            {% translate "Reset Filter" %}
                        </a>
                        <a class="btn btn-default pull-left" href="{% url 'structures:structure_list' %}" role="button">
                            {% translate "Clear Filter" %}
                        </a>
                        <button type="button" class="btn btn-default" data-dismiss="modal">
                            {% translate "Cancel" %}
                        </button>
                        <button type="submit" class="btn btn-primary">
                            {% translate "Apply Filter" %}
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <!-- Structure details modal -->
    <div class="modal" id="modalUpwellDetails" tabindex="-1" role="dialog" aria-labelledby="{% translate 'modalUpwellDetails '%}">
        <div class="modal-dialog" role="document">
            <div class="modal-content" id="modalUpwellDetailsContent">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Loading...</h4>
                </div>
                <div class="modal-body">
                </div>
            </div>
        </div>
    </div>

    <!-- Poco details modal -->
    <div class="modal" id="modalPocoDetails" tabindex="-1" role="dialog" aria-labelledby="modalPocoDetails">
        <div class="modal-dialog" role="document">
            <div class="modal-content" id="modalPocoDetailsContent">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Loading...</h4>
                </div>
                <div class="modal-body">
                </div>
            </div>
        </div>
    </div>

    <!-- Starbase details modal -->
    <div class="modal" id="modalStarbaseDetail" tabindex="-1" role="dialog" aria-labelledby="modalStarbaseDetail">
        <div class="modal-dialog" role="document">
            <div class="modal-content" id="modalStarbaseDetailContent">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Loading...</h4>
                </div>
                <div class="modal-body">
                </div>
            </div>
        </div>
    </div>

    <!-- Export to Javascript -->
    {{ data_export|json_script:"export-data" }}

{% endblock %}

{% block extra_javascript %}
    {% include 'bundles/datatables-js.html' %}
    <script
        type="application/javascript"
        src="{% static 'structures/vendor/datatables/plugins/filterDropDown.min.js' %}">
    </script>
    <script type="application/javascript" src="{% static 'structures/js/global.js' %}"></script>
    <script type="application/javascript" src="{% static 'structures/js/structures.js' %}"></script>

{% endblock %}

{% block extra_css %}
    {% include 'bundles/datatables-css.html' %}

    <link rel="stylesheet" href="{% static 'structures/css/global.css' %}" type="text/css" media="screen">
    <link rel="stylesheet" href="{% static 'structures/css/main.css' %}" type="text/css" media="screen">
    <link rel="stylesheet" href="{% static 'structures/css/structures.css' %}" type="text/css" media="screen">
{% endblock %}

{% block extra_script %}

{% endblock %}